# Generated by Django 5.2.6 on 2025-09-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cron_schedule',
            field=models.CharField(blank=True, help_text='Optional: cron pattern for scheduling', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalation_after',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivery_channel',
            field=models.CharField(default='in-app', max_length=40),
        ),
        migrations.AlterField(
            model_name='alert',
            name='delivery_type',
            field=models.CharField(choices=[('in-app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='in-app', max_length=50),
        ),
        migrations.AlterField(
            model_name='useralertpreference',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('features', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
